// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Janno Tjarks",
            "url": "https://tjarks.dev",
            "email": "janno.tjarks@mailbox.org"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Returns a small welcome message. This welcome page can be used as a very simple healthcheck.",
                "produces": [
                    "text/plain"
                ],
                "summary": "Returns a small welcome message",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/nic/update": {
            "get": {
                "description": "Set a DNS A Record by using the DynDNS Update API, also called the dyndns2 standard.",
                "produces": [
                    "text/plain"
                ],
                "summary": "Update IP address of a DNS Record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hostname which will be updated - Must be a Fully Qualified Domain Name",
                        "name": "hostname",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IP Address which will be set in Azure DNS - Must be a IPv4 Address",
                        "name": "myip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns the current version of azure-dyndns2 as json object.",
                "produces": [
                    "application/json"
                ],
                "summary": "Returns the current version of azure-dyndns2",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "azure-dyndns2",
	Description:      "Simple dyndns2-compatible web api for Azure DNS.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
